name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: macos-latest
    

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build amd64
        env:
          GOOS: darwin
          GOARCH: amd64
        run: |
          go build -o 55h .
          tar -czf 55h_${{ github.ref_name }}_darwin_amd64.tar.gz 55h

      - name: Build arm64
        env:
          GOOS: darwin
          GOARCH: arm64
        run: |
          go build -o 55h .
          tar -czf 55h_${{ github.ref_name }}_darwin_arm64.tar.gz 55h

      - name: Create Release and Upload Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "${{ github.ref_name }}" \
            --generate-notes \
            55h_${{ github.ref_name }}_darwin_amd64.tar.gz \
            55h_${{ github.ref_name }}_darwin_arm64.tar.gz
